name: CI

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pre commit
        run: |
          python -m pip install poetry
          poetry install
          poetry shell
          pre-commit run --all-files
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mypy
        run: |
          python -m pip install poetry
          poetry install
          poetry shell
          mypy --ignore-missing-imports services/TwitterSA
